export type UserRole = "user" | "admin";
export type AccountStatus = "Active" | "Pending" | "Restricted";
export type TransactionType = "deposit" | "withdrawal";
export type TransactionStatus = "pending" | "approved" | "rejected";

export interface UserProfile {
  uid: string;
  email: string;
  firstName: string;
  lastName: string;
  country: string;
  phone: string;
  city: string;
  status: AccountStatus;
  role: UserRole;
  balance: number;
  totalProfit: number;
  securityPin: string;
  bankingCode?: string; // Generated by admin
  withdrawalCode?: string; // Generated by admin
  codeExpiresAt?: number; // Epoch timestamp in ms when code expires
  codeTimerDuration?: number; // Duration set by admin in seconds
  codeTimerPaused?: boolean; // Whether timer is paused
  codeTimerPausedRemaining?: number; // Remaining seconds when paused
  onboarded: boolean;
  createdAt: any;
  bankDetails?: {
    bankName: string;
    accountName: string;
    city: string;
    swiftCode: string;
    accountNumber: string;
  };
  requireVerification?: boolean;
  verificationMessage?: string;
}

export interface Transaction {
  id: string;
  userId: string;
  userName: string;
  amount: number;
  type: TransactionType;
  status: TransactionStatus;
  rejectionReason?: string;
  bankDetails?: any;
  createdAt: any;
  updatedAt: any;
}

export interface ChatMessage {
  id: string;
  userId: string;
  senderId: string;
  text: string;
  isAdmin: boolean;
  createdAt: any;
}

export interface Notification {
  id: string;
  userId: string;
  title: string;
  message: string;
  read: boolean;
  createdAt: any;
}
